apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1-pod
          image: cursodocker03.azurecr.io/backend1
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          env:
            - name: SERVICE_API2_ENDPOINT
              value: http://backend2-svc/api
            - name: PORT
              value: '3010'
