version: '3.8'

services:
  wp:
    image: wordpress
    container_name: wp-web
    volumes:
      - $PWD/html:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - net-test
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wp-mysql
    volumes:
      - $PWD/data:/var/lib/mysql
      - $PWD/mysql-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    networks:
      - net-test

networks:
  net-test:
