apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-set
  labels:
    app: backend-rs
    env: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: contenedor1
          image: python:3.7-alpine
          command:
            [
              'sh',
              '-c',
              'echo "contenedor1" > index.html && python -m http.server 8081',
            ]
